eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.cloud.client.port}:${spring.application.name}:${random.value}-dev
